languageCode = "en-gb"
timeout = "300s"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
disableRSS      = false

# Why 97? Cos. Cos it's a prime number?
paginate = 97

[frontmatter]
date = ["date", "publishDate", "lastmod", ":git"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false
      # Changing this to false isn't the easy fix I want it to be
      # Ideally autolinking _wouldn't_ happen inside linkrot tags
      linkify = true

      [markup.goldmark.extensions.passthrough]
          enable = true
          [markup.goldmark.extensions.passthrough.delimiters]
            block = [['$$', '$$']]
            inline = [['$', '$']]
    [markup.goldmark.renderer]
      unsafe = true

[author]
  name = "JP Hastings-Edrei"
  email = "hello@byjp.me"

[taxonomies]
  series = 'series'
  tag = 'tags'
  topic = 'topics'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 MST"
  dateformHTML    = "2006-01-02T15:04:05-0700"

  # Metadata mostly used in document's head
  description = "JP Hastings-Spital: Software Engineer"
  keywords    = "homepage, blog, science, software, miriscient, programming, indieweb, memex"
  images      = [""]
  customJS    = ["/js/postcards-html.js"]

  justifyContent = true
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  clapshost = "byjp-claps.web.val.run"
  
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"
  
  [params.defaultSVG]
    post = "document"
    bookmark = "bookmark"
    article-bookmark = "bookmark"
    game-bookmark = "game"
    video-bookmark = "video"
    product-bookmark = "package"
    note = "message"
    photo = "camera"
    calendar = "calendar"
    review = "review"
    poetry = "feather"
    contact = "email"
    curiosities = "star"
    memex = "brain"
    reading-list = "book"

  [params.defaultEmoji]
    posts = "📔"
    bookmarks = "🔖"
    notes = "💬"
    photos = "📸"
    calendar = "🗓️"
    curiosities = "🤩"
    memex = "🧠"
    review = "📝"
    poetry = "🥁"
    reading-lists = "📚"
    contact-me = "📮"

[languages]
  [languages.en]
    title = "byJP"
    copyright = "CC BY-NC-SA 4.0"

    [languages.en.params.logo]
      logoHomeLink = "/"

    [[languages.en.params.social]]
      name = "email"
      url  = "mailto:hello@byjp.me"

    [[languages.en.params.social]]
      name = "bluesky"
      url  = "https://bsky.app/profile/byjp.me"

    [[languages.en.params.social]]
      name = "mastodon"
      url  = "https://hachyderm.io/@byjp"

    [[languages.en.params.social]]
      name = "signal"
      url  = "https://signal.me/#eu/IXpZjHz0782uKsD27aCw87_-PJXB1ZgzG58sVgiF8g2s5ThVioJIJ5WhFHSXQN8q"

    [[languages.en.params.social]]
      name = "github"
      url  = "https://github.com/jphastings"

    [[languages.en.params.social]]
      name = "keyoxide"
      url  = "https://id.byjp.me"
    
    [[languages.en.params.social]]
      name = "gpg"
      url  = "https://openpgpkey.byjp.me/.well-known/openpgpkey/byjp.me/hu/im4cc8qhazwkfsi65a8us1bc5gzk1o4p"
      rel  = "pgpkey authn"

  # You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact me"
        url = "/standing-invitation"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "curiosities"
        name = "Curiosities"
        url = "/curiosities"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "calendar"
        name = "Calendar"
        url = "/calendar"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "bookmarks"
        name = "Bookmarks"
        url = "/bookmarks"
        weight = 4
      [[languages.en.menu.main]]
        identifier = "memex"
        name = "Memex"
        url = "/memex"
        weight = 5
      [[languages.en.menu.main]]
        identifier = "photos"
        name = "Photos"
        url = "/photos"
        weight = 6
      [[languages.en.menu.main]]
        identifier = "notes"
        name = "Notes"
        url = "/notes"
        weight = 7
      [[languages.en.menu.main]]
        identifier = "reading-lists"
        name = "Reading lists"
        url = "/reading-lists"
        weight = 8
      [[languages.en.menu.main]]
        identifier = "post"
        name = "Posts"
        url = "/posts"
        weight = 9

[sitemap]
  filename = 'sitemap.xml'

[mediaTypes]
  [mediaTypes.'text/x-opml']
    suffixes = ['opml.xml']
  [mediaTypes.'text/gemini']
    suffixes = ['gmi']
[outputFormats]
  [outputFormats.opml]
    mediaType = 'text/x-opml'
    baseName = 'feeds'
  [outputFormats.calendar]
    baseName = 'events'
    name = 'calendar'
  [outputFormats.rss]
    baseName = 'index'
    name = 'rss'
  [outputFormats.gemini]
    name = 'Gemini'
    isPlainText = true
    isHTML = false
    mediaType = 'text/gemini'
    protocol = 'gemini://'
    permalinkable = true
    noUgly = true
  [outputFormats.api]
    name = 'JSON API'
    isPlainText = true
    isHTML = false
    mediaType = 'application/json'
    permalinkable = false
    noUgly = false
    notAlternative = true

[outputs]
  home = ["html", "rss", "gemini"]
  page = ["html", "gemini"]
  rss = ["rss"]
  section = ["html", "rss", "gemini"]
  taxonomy = ["html", "rss", "gemini"]
  term = ["html", "rss", "gemini"]

[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepQuotes = true
