languageCode = "en-gb"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
disableRSS      = false

paginate = 36

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false
    [markup.goldmark.renderer]
      unsafe = true

[author]
  name = "JP Hastings-Spital"
  email = "hello@byjp.me"

[taxonomies]
  series = 'series'
  tag = 'tags'


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 MST"
  dateformHTML    = "2006-01-02T15:04:05-0700"

  # Metadata mostly used in document's head
  description = "JP Hastings-Spital: Software Engineer"
  keywords    = "homepage, blog, science, software, miriscient, programming"
  images      = [""]
  customJS    = ["/js/postcards-html.js"]

  justifyContent = true
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

[languages]
  [languages.en]
    title = "byJP"
    copyright = "CC BY-NC-SA 4.0"

    [languages.en.params.logo]
      logoHomeLink = "/"

    [[languages.en.params.social]]
      name = "email"
      url  = "mailto:hello@byjp.me"

    [[languages.en.params.social]]
      name = "bluesky"
      url  = "https://bsky.app/profile/byjp.me"

    [[languages.en.params.social]]
      name = "mastodon"
      url  = "https://hachyderm.io/@byjp"

    [[languages.en.params.social]]
      name = "github"
      url  = "https://github.com/jphastings"

    [[languages.en.params.social]]
      name = "keyoxide"
      url  = "https://id.byjp.me"
    
    [[languages.en.params.social]]
      name = "gpg"
      url  = "https://openpgpkey.byjp.me/.well-known/openpgpkey/byjp.me/hu/im4cc8qhazwkfsi65a8us1bc5gzk1o4p"
      rel  = "pgpkey authn"

  # You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "curiosities"
        name = "Curiosities"
        url = "/curiosities"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "mail"
        name = ":postbox:"
        url = "/standing-invitation"

[sitemap]
  filename = 'sitemap.xml'
