# Important! This app needs a dedicated IP address to work properly
# Run `fly ips allocate-v4` after first deploy to buy one, then remove the shared IP and continue.

app = 'byjp-cc'
primary_region = 'lhr'

[build]

[[files]]
  guest_path = "/var/agate/certificates/byjp.cc/cert.der"
  secret_name = "AGATE_CERT"

[[files]]
  guest_path = "/var/agate/certificates/byjp.cc/key.der"
  secret_name = "AGATE_KEY"

[[services]]
  internal_port = 1965
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [services.concurrency]
    hard_limit = 5000
    soft_limit = 4000
    type       = "connections"

  [[services.ports]]
    port = 1965

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
