# https://taskfile.dev

version: '3'

# TODO: Handle commands in dotenv
# dotenv: ['.env']

env:
  DOMAIN: https://www.byjp.me
  HUGO_INDIEKIT_URL: https://indiekit.byjp.me{{.DOMAIN_SUFFIX}}
  HUGO_LAST_UPDATE_TIME:
    sh: git log -1 --format=%cI
  HUGO_LAST_UPDATE_HASH:
    sh: git log -1 --format=%h

tasks:
  check-links:
    cmds:
      - lychee --cache --require-https --config lychee.toml .

  dev:
    env:
      DOMAIN_SUFFIX: .test
    cmds: 
      - hugo server --minify --printUnusedTemplates -D --baseURL "${DOMAIN}${DOMAIN_SUFFIX}" --appendPort=false

  build:
    cmds:
      - hugo --cacheDir /tmp/hugo/cache --gc --minify --baseURL "${DOMAIN}"
      - pagefind

  import:
    dir: tools/
    cmds:
      - go run ./import/omnivore ../
      - go run ./import/webmentionio
