# https://taskfile.dev

version: '3'

# TODO: Handle commands in dotenv
# dotenv: ['.env']

env:
  DOMAIN: https://www.byjp.me

tasks:
  check-links:
    cmds:
      - rm -rf ./public/
      - lychee --cache --suggest --require-https .
  dev:
    env:
      DOMAIN_SUFFIX: .test
    cmds:
      - |
        set -o allexport; source .env; set +o allexport
        hugo server --minify --printUnusedTemplates -D --baseURL "${DOMAIN}${DOMAIN_SUFFIX}" --appendPort=false
  build:
    cmds:  
      - hugo --cacheDir /tmp/hugo/cache --gc --minify --baseURL "${DOMAIN}"
      - npm_config_yes=true npx pagefind@latest
  import:
    cmds: 
      - cd ./tools/import/omnivore && go run .
