on:
  push:
    branches: ["main"]
    paths-ignore:
      - indiekit/**
      - .github/workflows/indiekit-docker.yml
      - tools/**
  schedule:
    # Rebuild every day, to update 'year relative' dates, change now page & calendar
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache Hugo persistent info
        uses: https://code.forgejo.org/actions/cache@v4
        env:
          cache-name: hugo-persistent-cache
        with:
          path: /tmp/hugo
          key: www.byjp.me-hugo-persistent-info
      - name: Build site
        uses: https://git.byjp.me/jp/hugo-tasks@v0.1

      - name: Publish website
        run: |
          rm -r /pages/www.byjp.me/* /pages/www.byjp.me/.*
          cp -r ./public/. /pages/www.byjp.me
      
      - name: Build Gemini capsule
        uses: https://git.byjp.me/jp/hugo-tasks@v0.1
        with:
          tasks: gemini-reduce

      - name: Publish Gemini capsule
        run: |
          rm -r /gemini/www.byjp.me/* /gemini/www.byjp.me/.*
          cp -r ./public/. /gemini/www.byjp.me
