on:
  push:
    branches: ["main"]
    paths-ignore:
      - indiekit/**
      - .github/workflows/indiekit-docker.yml
      - tools/**
  schedule:
    # Rebuild every day, to update 'year relative' dates, change now page & calendar
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache Hugo persistent info
        uses: https://code.forgejo.org/actions/cache@v4
        env:
          key: www.byjp.me-hugo-persistent-info
          cache-name: hugo-persistent-cache
        with:
          path: /tmp/hugo
      - name: Build site
        uses: https://git.byjp.me/jp/hugo-tasks@v0.1.0

      # TODO: Move site
      
      - name: Build Gemini capsule
        uses: https://git.byjp.me/jp/hugo-tasks@v0.1.0
        with:
          tasks: gemini-reduce

      # TODO: Move gemini
