on:
  push:
    branches: ["main"]
    paths-ignore:
      - indiekit/**
      - .github/workflows/indiekit-docker.yml
      - tools/**
  schedule:
    # Rebuild every day, to update 'year relative' dates, change now page & calendar
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    container:
      image: git.byjp.me/jp/hugo-tasks:latest
      volumes:
        - /pages/www.byjp.me/:/pages/www.byjp.me/
        - /gemini/www.byjp.me/:/gemini/www.byjp.me/
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache Hugo persistent info
        uses: https://code.forgejo.org/actions/cache@v4
        env:
          cache-name: hugo-persistent-cache
        with:
          path: /tmp/hugo
          key: www.byjp.me-hugo-persistent-info

      - name: Build + publish web site + gemini capsule
        run: |
          task build
          rsync -a --delete ./public/. /pages/www.byjp.me
          task gemini-reduce
          rsync -a --delete ./public/. /gemini/www.byjp.me
