name: Build Indiekit Docker container

on:
  push:
    branches: ["main"]
    paths:
      - indiekit/**

  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write

concurrency:
  group: "docker"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  image-releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Authenticate with Github Container Repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: by-jp/indiekit.byjp.me
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./indiekit
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
