name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
    paths-ignore:
      - indiekit/**
      - .github/workflows/indiekit-docker.yml
      - tools/**
  schedule:
    # Rebuild every day, to update 'year relative' dates, change now page & calendar
    - cron: '0 0 * * *'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.147.4
      PAGEFIND_VERSION: 1.4.0
      TASK_VERSION: 3.43.3
    steps:
      - name: Install Hugo CLI
        run: |
          wget -q -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Pagefind CLI
        run: |
          wget -q -O ${{ runner.temp }}/pagefind.tar.gz https://github.com/CloudCannon/pagefind/releases/download/v${PAGEFIND_VERSION}/pagefind-v${PAGEFIND_VERSION}-x86_64-unknown-linux-musl.tar.gz \
          && tar -xpf ${{ runner.temp }}/pagefind.tar.gz pagefind \
          && mv pagefind /usr/local/bin/pagefind
      - name: Install Task CLI
        run: |
          wget -q -O ${{ runner.temp }}/task.tar.gz https://github.com/go-task/task/releases/download/v${TASK_VERSION}/task_linux_amd64.tar.gz \
          && tar -xpf ${{ runner.temp }}/task.tar.gz task \
          && mv task /usr/local/bin/task
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./www.byjp.me
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Cache Hugo persistent info
        uses: actions/cache@v3
        env:
          cache-name: hugo-persistent-cache
        with:
          path: /tmp/hugo
          key: ${{ env.cache-name }}
      - name: Build site
        working-directory: ./www.byjp.me
        run: |
          task build
          mv ./public/index.redirects ../new_redirects

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: site
          path: ./www.byjp.me/public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: site
